spring.application.name=EC-OnlineBookStore
server.port=7071
spring.config.import: optional:configserver:http://localhost:6666
# ===============================
# DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/onlinebookstore
spring.datasource.username=root
spring.datasource.password=12345

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update

# SHOW SQL QUERY IN CONSOLE
spring.jpa.show-sql=true

# MYSQL DIALECT
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# FORMAT SQL
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER PORT
# ===============================

#server.port=8080